### ISSUE TITLE
Fatal error C1083 while installing

### ISSUE THREAD

**Issue by feimosi** [flosse/node-plc#2]
Can't be installed on Windows 10. I get the following error;

```
..\..\..\src\libnodave\nodave.c(47): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory [F:\CS\slushTest\node_modules\plc\build\src\libnodave\nodave.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd F:\CS\slushTest\node_modules\plc
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON mean@0.0.1 No repository field.
npm WARN EPACKAGEJSON mean@0.0.1 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "plc"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! plc@0.2.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the plc@0.2.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the plc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls plc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\CS\slushTest\npm-debug.log
```

Nothing really helps. I've tried updating everything.

**Comment by flosse** [comment]
Oh...I never used it on windows at all :-\ The first line tells `Cannot open include file: 'sys/time.h'` so I guess the header needs to be modified.

**Comment by flosse** [comment]
you might need to change something [here](https://github.com/flosse/node-plc/blob/master/src/node_nodave.h#L5) because now you'll always have `LINUX` defined even if you're using windows. Feel free to create a PR.
